# 创建数组对象

In [1]:
import numpy as np

创建一维数组

In [2]:
arr1 = np.array([1,2,3,4])
print('创建的数组为：\n', arr1)

创建的数组为：
 [1 2 3 4]


创建二维数组

In [3]:
arr2 = np.array([[1,2,3,4], [4,5,6,7], [7,8,9,10]])
print('创建的二维数组：\n', arr2)

创建的二维数组：
 [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [4]:
print('数组维度为：', arr2.shape)

数组维度为： (3, 4)


In [5]:
print('数组类型为：', arr2.dtype)

数组类型为： int32


In [6]:
print('数组元素个数为：', arr2.size)

数组元素个数为： 12


In [7]:
print('数组每个元素大小为：', arr2.itemsize)

数组每个元素大小为： 4


修改数组的shape属性

In [8]:
arr2.shape = 4,3
print('重新设置shape后的arr2是：', arr2)

重新设置shape后的arr2是： [[ 1  2  3]
 [ 4  4  5]
 [ 6  7  7]
 [ 8  9 10]]


arange 函数类似于 Python 自带的函数 range，通过指定开始值、终值和步长来创建一维数组，创建的数组**不含终值**。

In [9]:
print('使用arange函数创建的数组为：\n', np.arange(0,1,0.1))

使用arange函数创建的数组为：
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


linspace函数通过指定开始值、终值和元素个数来创建一维数组，默认设置**包括终值**，这一点需要和arange函数区分。

In [10]:
print('使用linspace函数创建的数组为：', np.linspace(0,1,12))

使用linspace函数创建的数组为： [0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


logspace函数和linspace函数类似，它创建的是等比数列.

生成1（10^0）～100（10^2）的20个元素的等比数列:

In [12]:
print('使用logspace函数创建的数列为：\n', np.logspace(0,2,20))

使用logspace函数创建的数列为：
 [  1.           1.27427499   1.62377674   2.06913808   2.6366509
   3.35981829   4.2813324    5.45559478   6.95192796   8.8586679
  11.28837892  14.38449888  18.32980711  23.35721469  29.76351442
  37.92690191  48.32930239  61.58482111  78.47599704 100.        ]


zeros函数用来创建值全部为0的数组，即创建的数组值全部填充为0。

In [13]:
print('使用zeros函数创建的数组为：\n', np.zeros((2,3)))

使用zeros函数创建的数组为：
 [[0. 0. 0.]
 [0. 0. 0.]]


eye函数用来生成主对角线上的元素为1，其他的元素为0的数组，类似单位矩阵。

In [14]:
print('使用eye函数创建的数组为：\n', np.eye(3))

使用eye函数创建的数组为：
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


diag 函数创建类似对角的数组，即除对角线以外的其他元素都为 0，对角线上的元素可以是0或其他值。

In [17]:
print('使用diag函数创建的数组为：\n', np.diag([1,2,3,4]))

使用diag函数创建的数组为：
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


ones函数用来创建元素全部为1的数组，即创建的数组元素全部填充为1。

In [18]:
print('使用ones函数创建的数组为：\n', np.ones((5,3)))

使用ones函数创建的数组为：
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


数组数据类型转换

In [19]:
# 整数转浮点
print('42的转换结果是：', np.float64(42))

42的转换结果是： 42.0


In [21]:
# 浮点转整型
print('42.0转整型的结果是：', np.int8(42.0))
print('42.6转整型的结果是：', np.int8(42.6))

42.0转整型的结果是： 42
42.6转整型的结果是： 42


In [23]:
# 整型转布尔型
print('42转布尔型的结果是：', np.bool(42))
print('0转布尔型的结果是：', np.bool(0))
print('-1转布尔型的结果是：', np.bool(-1))

42转布尔型的结果是： True
0转布尔型的结果是： False
-1转布尔型的结果是： True


In [24]:
# 布尔型转浮点型
print('True转换结果为：', np.float(True))
print('False转换结果为：', np.float(False))

True转换结果为： 1.0
False转换结果为： 0.0


创建一个存储餐饮企业库存信息的数据类型：

In [30]:
# 这里定义一个numpy.dtype类型的数组，储存变量类型的名字（注意不是变量名），变量类型
df = np.dtype([('name', np.str, 40), ('numitems', np.int64), ('price', np.float64)])
print('数据类型为：', df)
print('df的数据类型为：', type(df))

数据类型为： [('name', '<U40'), ('numitems', '<i8'), ('price', '<f8')]
df的数据类型为： <class 'numpy.dtype'>


查看数据类型：

In [26]:
print('name的数据类型为：', df['name'])
print('name的数据类型为：', np.dtype(df['name']))

name的数据类型为： <U40
name的数据类型为： <U40


在使用array函数创建数组时，数组的数据类型默认是浮点型。自定义数组数据，则可以预先指定数据类型。

In [32]:
itemz = np.array([('tomatoes',42,4.14), ('cabbages',13,1.72)], dtype=df)
print('自定义数据为：\n', itemz)

自定义数据为：
 [('tomatoes', 42, 4.14) ('cabbages', 13, 1.72)]


# 生成随机数

random函数是最常见的生成随机数的方法。

In [34]:
print('生成的随机数组为：\n', np.random.random(100))

生成的随机数组为：
 [0.53512461 0.70808258 0.17500974 0.39384188 0.81008378 0.87728734
 0.10078651 0.37779419 0.24296355 0.65500501 0.15293905 0.63945218
 0.72300847 0.87863774 0.23631927 0.43383814 0.73151832 0.58080024
 0.86122521 0.25099191 0.47681461 0.10711493 0.91606302 0.07582022
 0.21805276 0.68986322 0.16384281 0.55815556 0.38780069 0.12949231
 0.38955547 0.48060031 0.49595465 0.20446952 0.40123189 0.77235602
 0.40120768 0.64734053 0.93929258 0.85115919 0.77238734 0.96099892
 0.30847099 0.37192121 0.02858069 0.28056454 0.28399136 0.6209102
 0.20276012 0.81082665 0.03389028 0.03339573 0.14301495 0.65455465
 0.75005175 0.8731061  0.9700825  0.63498977 0.4085396  0.31472134
 0.38702648 0.80885039 0.76659699 0.58019705 0.62913639 0.06157813
 0.36704494 0.61717578 0.5953275  0.10353126 0.09368567 0.56298403
 0.75469228 0.463341   0.70849601 0.46740867 0.16768959 0.33967017
 0.84003959 0.55770239 0.84893678 0.99160102 0.71951242 0.27624433
 0.94599712 0.66986274 0.12924602 0.11784818 0.11416

rand函数可以生成服从均匀分布的随机数。

In [35]:
print('生成的随机数组为：\n', np.random.rand(10,5))

生成的随机数组为：
 [[0.27629335 0.18097882 0.46418704 0.44805269 0.91703815]
 [0.03907754 0.80143607 0.23375211 0.66768166 0.20202331]
 [0.84388778 0.90460068 0.7009211  0.28264283 0.31065263]
 [0.05608771 0.2202155  0.07643711 0.52767877 0.08090679]
 [0.90262315 0.50182762 0.98334533 0.64393528 0.75926621]
 [0.06472867 0.62673117 0.38682385 0.66780839 0.88221153]
 [0.79339615 0.60474125 0.02813947 0.31512082 0.91816814]
 [0.11955316 0.69572146 0.20472403 0.90720693 0.93108466]
 [0.29494944 0.12210327 0.54939175 0.75747993 0.49445401]
 [0.0033159  0.88486848 0.30475325 0.96804736 0.496968  ]]


randn函数可以生成服从正态分布的随机数。

In [37]:
print('生成的随机数组为：', np.random.randn(10,5))

生成的随机数组为： [[ 0.49492421  1.6982712  -0.89235274  0.51603011  1.29650734]
 [ 2.91485672 -0.30309006  1.36789507 -0.13785396  1.83574932]
 [-0.92578284 -1.43379814 -1.65148887  1.07673099  0.12398204]
 [ 0.24033456  0.52543983  0.57788935  0.30368441  1.64798516]
 [-1.11257293  0.14298487 -0.34874862  1.39823967 -0.43908693]
 [ 1.6884775  -1.57157071  0.38288867 -0.97909281  0.68918168]
 [ 0.75547217  0.31920862 -0.39256072 -0.64559727 -0.05912932]
 [ 0.54380624 -1.12970282  0.98335623  0.59434367 -0.13896713]
 [-0.18885582 -0.08458896 -0.96299489  1.28005493  0.13736475]
 [-0.37867905 -0.4818016  -1.78226549  0.28458429  0.51108162]]


randint函数可以生成给定上下限范围的随机数。格式：numpy.random.randint(low, high=None, size=None,dtype='l')。其中，low为最小值，high为最大值，size为数组的shape。

In [38]:
print('生成的随机数组为：\n', np.random.randint(1,10,size=[2,5]))

生成的随机数组为：
 [[3 1 3 8 9]
 [5 5 1 5 8]]


# 通过索引访问数组

一维数组的索引方法很简单，与Python中的list的索引方法一致。

In [39]:
arr = np.arange(10)
print('数组为：\n', arr)
# 用整数作为下标可获取数组中的某个元素
print('索引结果为：', arr[5])

数组为：
 [0 1 2 3 4 5 6 7 8 9]
索引结果为： 5


In [40]:
# 范围用作下标，获取数组切片，含arr[3]，不含arr[5]
print('索引结果为：', arr[3:5])

索引结果为： [3 4]


In [41]:
# 省略开始下标从头开始取
print('索引结果为：', arr[:5])

索引结果为： [0 1 2 3 4]


In [42]:
# 下标使用负数，-1表示从数组最后往前数第一个元素
print('索引结果为：', arr[-1])

索引结果为： 9


In [45]:
# 下标还可以用来修改元素的值
arr[3:5] = [100,101]
print('修改元素后的数组为：\n', arr)

修改元素后的数组为：
 [  0   1   2 100 101   5   6   7   8   9]


In [46]:
# 范围中的第三个参数表示步长
print('索引结果为：', arr[1:-1:2])

索引结果为： [  1 100   5   7]


In [47]:
# 步长为负数时，开始下标必须大于结束下标
print('索引结果为：', arr[5:1:-1])

索引结果为： [  5 101 100   2]


多维数组的每一个维度都有一个索引，各个维度的索引之间用逗号隔开。

In [48]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11]])
print('创建的二维数组为：\n', arr)

创建的二维数组为：
 [[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]]


多维数组同样也可以使用整数序列和布尔值索引进行访问:

In [49]:
# 从两个序列的对应位置取出两个整数组成下标：arr[0,1],arr[1,2],arr[2,3]
print('索引结果为：', arr[[(0,1,2),(1,2,3)]])

索引结果为： [ 2  6 10]


D:\anaconda3.7\path\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  


In [51]:
# 索引第2、3行中第0、2、3列的元素
print('索引结果为：\n', arr[1:,(0,2,3)])

索引结果为：
 [[ 4  6  7]
 [ 7  9 10]]


# 变换数组形态

在NumPy中，常用reshape函数改变数组的“形状”，也就是改变数组的维度。其参数为一个正整数元组，分别指定数组在每个维度上的大小。

reshape函数在改变原始数据的形状的同时不改变原始数据的值。如果指定的维度和数组的元素数目不吻合，则函数将抛出异常

In [54]:
# 创建一维数组
arr = np.arange(12)
print('创建的一维数组为：\n', arr)

创建的一维数组为：
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [55]:
# 设置数组形状
print('新的一维数组为：\n', arr.reshape(3,4))

新的一维数组为：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [56]:
# 查看数组维度
print('数组维度为：', arr.reshape(3,4).ndim)

数组维度为： 2


在NumPy中，可以使用ravel函数完成数组展平工作。

In [58]:
# 创建二维数组
arr = np.arange(12).reshape(3,4)
print('创建的二维数组为：\n', arr)
print('数组展平后为：\n', arr.ravel())

创建的二维数组为：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
数组展平后为：
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


flatten函数也可以完成数组展平工作。与ravel函数的区别在于，flatten函数可以选择横向或纵向展平。

In [61]:
print('数组横向展平：\n', arr.flatten())
print('数组纵向展平：\n', arr.flatten('F'))

数组横向展平：
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
数组纵向展平：
 [ 0  4  8  1  5  9  2  6 10  3  7 11]


横向组合是将ndarray对象构成的元组作为参数，传给hstack函数。

In [63]:
arr1 = np.arange(12).reshape(3,4)
print('创建的数组1为：\n', arr1)
arr2 = arr1 * 3
print('创建的数组2为：\n', arr2)
print('横向组合：', np.hstack((arr1,arr2)))

创建的数组1为：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
创建的数组2为：
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
横向组合： [[ 0  1  2  3  0  3  6  9]
 [ 4  5  6  7 12 15 18 21]
 [ 8  9 10 11 24 27 30 33]]


纵向组合同样是将ndarray对象构成的元组作为参数，只不过传给vstack函数。

In [65]:
print('横向组合为：', np.vstack((arr1,arr2)))

横向组合为： [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


concatenate函数也可以实现数组的横向组合和纵向组合，其中参数axis=1时按照横轴组合，参数axis = 0时按照纵轴组合

In [66]:
print('横向组合为：\n', np.concatenate((arr1,arr2), axis=1))

横向组合为：
 [[ 0  1  2  3  0  3  6  9]
 [ 4  5  6  7 12 15 18 21]
 [ 8  9 10 11 24 27 30 33]]


In [67]:
print('纵向组合为：\n', np.concatenate((arr1,arr2), axis=0))

纵向组合为：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


使用hsplit函数可以对数组进行横向分割，以ndarray对象构成的元组作为参数。

In [69]:
arr = np.arange(16).reshape(4,4)
print('创建的二维数组为：\n', arr)
print('横向分隔为：\n', np.hsplit(arr,2))

创建的二维数组为：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
横向分隔为：
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


使用vsplit函数可以对数组进行纵向分割，以ndarray对象构成的元组作为参数。

In [71]:
print('横向分隔为：\n', np.vsplit(arr,2))

横向分隔为：
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


split函数同样可以实现数组分割。在参数axis=1时，可以进行横向分割；在参数axis=0时，可以进行纵向分割，如代码2-29所示。