# 创建NumPy矩阵

在NumPy中，矩阵是ndarray的子类。在NumPy中，数组和矩阵有着重要的区别。NumPy提供了两个基本的对象：一个N维数组对象和一个通用函数对象。其他对象都是在它们之上构建的。

矩阵是继承自NumPy数组对象的二维数组对象。与数学概念中的矩阵一样，NumPy中的矩阵也是二维的。

使用mat函数创建矩阵时，若输入matrix或ndarray对象，则不会为它们创建副本。因此，调用mat函数和调用matrix(data,copy=False)等价。

In [1]:
import numpy as np

In [2]:
# 使用分号分隔开数据
matr1 = np.mat('1 2 3;4 5 6;7 8 9')
print('创建的矩阵为：\n', matr1)

创建的矩阵为：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
matr2 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print('创建的矩阵为：\n', matr2)

创建的矩阵为：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


很多时候会根据小的矩阵创建大的矩阵，即将小矩阵组合成大矩阵。在NumPy中，可以使用bmat分块矩阵（block matrix）函数实现。

In [5]:
arr1 = np.eye(3)
print('创建的数组1为：\n', arr1)

创建的数组1为：
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
arr2 = 3 * arr1
print('创建的数组2位为：\n', arr2)

创建的数组2位为：
 [[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]


In [8]:
print('创建的矩阵为：\n', np.bmat('arr1 arr2; arr1 arr2'))

创建的矩阵为：
 [[1. 0. 0. 3. 0. 0.]
 [0. 1. 0. 0. 3. 0.]
 [0. 0. 1. 0. 0. 3.]
 [1. 0. 0. 3. 0. 0.]
 [0. 1. 0. 0. 3. 0.]
 [0. 0. 1. 0. 0. 3.]]


在NumPy中，矩阵计算是针对整个矩阵中的每个元素进行的。与使用for循环相比，其在运算速度上更快。

In [9]:
# 创建矩阵
matr1 = np.mat('1 2 3;4 5 6;7 8 9')
print('创建的矩阵为：\n', matr1)

创建的矩阵为：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# 矩阵与数相乘
matr2 = matr1 * 3
print('创建的矩阵为：\n', matr2)

创建的矩阵为：
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [11]:
# 矩阵相加
print('矩阵相加的结果为：\n', matr1+matr2)

矩阵相加的结果为：
 [[ 4  8 12]
 [16 20 24]
 [28 32 36]]


In [12]:
# 矩阵相减
print('矩阵相减的结果为：\n', matr1-matr2)

矩阵相减的结果为：
 [[ -2  -4  -6]
 [ -8 -10 -12]
 [-14 -16 -18]]


In [13]:
# 矩阵相乘
print('矩阵相乘的结果为：\n', matr1*matr2)

矩阵相乘的结果为：
 [[ 90 108 126]
 [198 243 288]
 [306 378 450]]


查看矩阵属性

In [15]:
print('矩阵转置结果：\n', matr1.T)

矩阵转置结果：
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [16]:
print('矩阵共轭转置结果为：\n', matr1.H)

矩阵共轭转置结果为：
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [17]:
print('矩阵的逆矩阵结果为：\n', matr1.I)

矩阵的逆矩阵结果为：
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [18]:
print('矩阵的二维数组结果为：\n', matr1.A)

矩阵的二维数组结果为：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


ufunc 函数全称为通用函数，是一种能够对数组中的所有元素进行操作的函数。ufunc函数是针对数组进行操作的，并且都以NumPy数组作为输出，因此不需要对数组的每一个元素都进行操作。对一个数组进行重复运算时，使用ufunc函数比使用math库中的函数效率要高很多。

In [20]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print('数组相加的结果为：\n', x+y)

数组相加的结果为：
 [5 7 9]


In [21]:
print('数组相减结果为：', x-y)

数组相减结果为： [-3 -3 -3]


In [22]:
print('数组相乘结果为：\n', x*y)

数组相乘结果为：
 [ 4 10 18]


In [23]:
print('数组相除的结果为：\n', x/y)

数组相除的结果为：
 [0.25 0.4  0.5 ]


In [24]:
print('数组的幂运算：\n', x**y)

数组的幂运算：
 [  1  32 729]


ufunc 中也可以用完整的比较运算：>、<、==、>=、<=、!=。比较运算返回的结果是一个布尔数组，其每个元素为数组对应元素的比较结果。

In [25]:
x = np.array([1,3,5])
y = np.array([2,3,4])
print('数组的比较结果为：\n', x>y)

数组的比较结果为：
 [False False  True]


In [26]:
print('数组的比较结果为：\n', x==y)

数组的比较结果为：
 [False  True False]


In [27]:
print('数组的比较结果为：\n', x>=y)

数组的比较结果为：
 [False  True  True]


In [28]:
print('数组的比较结果为：\n', x!=y)

数组的比较结果为：
 [ True False  True]


在NumPy逻辑运算中，np.all函数表示逻辑and，np.any函数表示逻辑or。

In [30]:
print('逻辑运算结果为：\n', np.all(x==y))

逻辑运算结果为：
 False


ufunc函数的广播机制:

广播（Broadcasting）是指不同形状的数组之间执行算术运算的方式。当使用ufunc函数进行数组计算时，ufunc函数会对两个数组的对应元素进行计算。进行这种计算的前提是两个数组的shape一致。若两个数组的shape不一致，则NumPy会实行广播机制。NumPy中的广播机制并不容易理解，特别是在进行高维数组计算的时候。为了更好地使用广播机制，需要遵循4个原则。

* 让所有的输入数组向其中shape最长的数组看齐，shape中不足的部分通过在前面加1补齐;
* 输出数组的shape是输入数组shape的各个轴上的最大值;
* 如果输入数组的某个轴和输出数组的对应轴的长度相同或者其长度为 1，则这个数组能够用来计算，否则出错;
* 当输入数组的某个轴的长度为1时，沿着此轴运算时使用此轴上的第一组值。

一维数组的广播机制

In [33]:
arr1 = np.array([[0,0,0], [1,1,1], [2,2,2], [3,3,3]])
print('创建的数组1为：\n', arr1)

创建的数组1为：
 [[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]


In [35]:
print('数组1的shape为:', arr1.shape)

数组1的shape为: (4, 3)


In [36]:
arr2 = np.array([1,2,3])
print('创建的数组2为：\n', arr2)

创建的数组2为：
 [1 2 3]


In [37]:
print('数组2的shape为:', arr2.shape)

数组2的shape为: (3,)


In [38]:
print('数组相加结果为：', arr1+arr2)

数组相加结果为： [[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


二维数组的广播机制

In [39]:
arr1 = np.array([[0,0,0], [1,1,1], [2,2,2], [3,3,3]])
print('创建的数组1为：\n', arr1)

创建的数组1为：
 [[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]


In [41]:
print('数组1的shape为：', arr1.shape)

数组1的shape为： (4, 3)


In [42]:
arr2 = np.array([1,2,3,4]).reshape((4,1))
print('创建的数组2为：\n', arr2)

创建的数组2为：
 [[1]
 [2]
 [3]
 [4]]


In [43]:
print('数组2的shape为：', arr2.shape)

数组2的shape为： (4, 1)


In [45]:
print('数组相加的结果为：\n', arr1+arr2)

数组相加的结果为：
 [[1 1 1]
 [3 3 3]
 [5 5 5]
 [7 7 7]]
