# 实训1 创建数组并进行运算

In [1]:
import numpy as np

In [2]:
 # 创建一个数值范围为0～1，间隔为0.01的数组
arr1 = np.arange(0, 1, 0.01)
print('创建的数组为：\n', arr1)

创建的数组为：
 [0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]


In [3]:
# 创建100个服从正态分布的随机数数组
arr2 = np.random.randn(100)
print('创建的服从正态分布的随机数数组为：\n', arr2)

创建的服从正态分布的随机数数组为：
 [ 2.30435552e+00 -6.46024994e-01 -5.55421889e-01 -7.71966920e-01
 -4.74580085e-01  1.77320368e-01  1.12516091e+00 -7.45235709e-02
 -2.13811635e-01 -1.78942174e+00 -3.79954344e-01  1.46979595e+00
  1.84123445e-01  2.73884461e-01 -1.04205208e+00 -7.99224930e-01
 -1.01207036e+00  6.29837877e-01 -7.42101524e-01  2.72971384e-01
 -1.32054922e-01  8.82581017e-02 -6.04596756e-01 -2.40092879e-01
 -1.92429814e-01 -8.66829728e-01 -6.25728404e-01  1.50805731e-01
 -4.77018344e-01 -1.45631114e+00 -1.59464958e+00  1.14446555e+00
  5.34596127e-01 -2.07989074e+00  3.02188982e-01 -3.08257229e-01
 -1.51473365e+00 -7.80984878e-01  7.75282217e-01 -1.03128677e-01
  9.60071618e-01  1.41693509e+00 -1.21532637e+00 -7.96263318e-01
 -7.19382761e-01 -7.59557863e-01  3.31230117e-01  4.10042082e-01
  2.10173005e-01 -1.04327324e+00  2.85333784e-01  1.73184006e+00
  1.01028724e+00  2.38335062e-01  1.85698699e-01  3.47563687e-01
  9.84296484e-01 -1.97988977e+00 -1.93079467e-01  3.46943921e-01
 -3.40

In [5]:
# 数组的四则运算
print('数组相加的结果为：\n', arr1+arr2)

数组相加的结果为：
 [ 2.30435552 -0.63602499 -0.53542189 -0.74196692 -0.43458009  0.22732037
  1.18516091 -0.00452357 -0.13381163 -1.69942174 -0.27995434  1.57979595
  0.30412344  0.40388446 -0.90205208 -0.64922493 -0.85207036  0.79983788
 -0.56210152  0.46297138  0.06794508  0.2982581  -0.38459676 -0.01009288
  0.04757019 -0.61682973 -0.3657284   0.42080573 -0.19701834 -1.16631114
 -1.29464958  1.45446555  0.85459613 -1.74989074  0.64218898  0.04174277
 -1.15473365 -0.41098488  1.15528222  0.28687132  1.36007162  1.82693509
 -0.79532637 -0.36626332 -0.27938276 -0.30955786  0.79123012  0.88004208
  0.690173   -0.55327324  0.78533378  2.24184006  1.53028724  0.76833506
  0.7256987   0.89756369  1.54429648 -1.40988977  0.38692053  0.93694392
  0.25910715 -0.24995963 -0.08158894  2.91234454  1.25821217  1.5812337
 -0.26772931  1.23115957 -0.09992354  0.53167008  1.08268524  0.14404764
 -0.16061173  0.23932422  2.87798927  0.45214758  0.50546902  0.7843051
  1.0657419  -0.08091325  2.69146832  1.49

In [6]:
# 数组相减
print('数组的相减的结果为：\n', arr1-arr2)

数组的相减的结果为：
 [-2.30435552  0.65602499  0.57542189  0.80196692  0.51458009 -0.12732037
 -1.06516091  0.14452357  0.29381163  1.87942174  0.47995434 -1.35979595
 -0.06412344 -0.14388446  1.18205208  0.94922493  1.17207036 -0.45983788
  0.92210152 -0.08297138  0.33205492  0.1217419   0.82459676  0.47009288
  0.43242981  1.11682973  0.8857284   0.11919427  0.75701834  1.74631114
  1.89464958 -0.83446555 -0.21459613  2.40989074  0.03781102  0.65825723
  1.87473365  1.15098488 -0.39528222  0.49312868 -0.56007162 -1.00693509
  1.63532637  1.22626332  1.15938276  1.20955786  0.12876988  0.05995792
  0.269827    1.53327324  0.21466622 -1.22184006 -0.49028724  0.29166494
  0.3543013   0.20243631 -0.42429648  2.54988977  0.77307947  0.24305608
  0.94089285  1.46995963  1.32158894 -1.65234454  0.02178783 -0.2812337
  1.58772931  0.10884043  1.45992354  0.84832992  0.31731476  1.27595236
  1.60061173  1.22067578 -1.39798927  1.04785242  1.01453098  0.7556949
  0.4942581   1.66091325 -1.09146832  0.1

In [7]:
# 数据相乘
print('数组相乘的结果为：\n', arr1*arr2)

数组相乘的结果为：
 [ 0.00000000e+00 -6.46024994e-03 -1.11084378e-02 -2.31590076e-02
 -1.89832034e-02  8.86601839e-03  6.75096547e-02 -5.21664996e-03
 -1.71049308e-02 -1.61047957e-01 -3.79954344e-02  1.61677554e-01
  2.20948134e-02  3.56049800e-02 -1.45887291e-01 -1.19883740e-01
 -1.61931257e-01  1.07072439e-01 -1.33578274e-01  5.18645630e-02
 -2.64109845e-02  1.85342014e-02 -1.33011286e-01 -5.52213621e-02
 -4.61831554e-02 -2.16707432e-01 -1.62689385e-01  4.07175474e-02
 -1.33565136e-01 -4.22330231e-01 -4.78394874e-01  3.54784320e-01
  1.71070761e-01 -6.86363944e-01  1.02744254e-01 -1.07890030e-01
 -5.45304112e-01 -2.88964405e-01  2.94607242e-01 -4.02201839e-02
  3.84028647e-01  5.80943389e-01 -5.10437074e-01 -3.42393227e-01
 -3.16528415e-01 -3.41801038e-01  1.52365854e-01  1.92719779e-01
  1.00883042e-01 -5.11203888e-01  1.42666892e-01  8.83238432e-01
  5.25349367e-01  1.26317583e-01  1.00277297e-01  1.91160028e-01
  5.51206031e-01 -1.12853717e+00 -1.11986091e-01  2.04696913e-01
 -2.04535707e-

In [8]:
# 数据相除
print('数组相除的结果为：\n', arr1/arr2)

数组相除的结果为：
 [ 0.00000000e+00 -1.54792773e-02 -3.60086637e-02 -3.88617688e-02
 -8.42850369e-02  2.81975504e-01  5.33257060e-02 -9.39300133e-01
 -3.74161117e-01 -5.02955775e-02 -2.63189516e-01  7.48403207e-02
  6.51736666e-01  4.74652704e-01 -1.34350291e-01 -1.87681833e-01
 -1.58091776e-01  2.69910728e-01 -2.42554414e-01  6.96043655e-01
 -1.51452136e+00  2.37938496e+00 -3.63878896e-01 -9.57962607e-01
 -1.24720798e+00 -2.88407275e-01 -4.15515738e-01  1.79038289e+00
 -5.86979523e-01 -1.99133270e-01 -1.88129106e-01  2.70868791e-01
  5.98582713e-01 -1.58662180e-01  1.12512375e+00 -1.13541538e+00
 -2.37665547e-01 -4.73760773e-01  4.90144094e-01 -3.78168336e+00
  4.16635585e-01  2.89356938e-01 -3.45586183e-01 -5.40022365e-01
 -6.11635452e-01 -5.92449926e-01  1.38876260e+00  1.14622382e+00
  2.28383279e+00 -4.69675614e-01  1.75233368e+00  2.94484468e-01
  5.14705103e-01  2.22376010e+00  2.90793637e+00  1.58244379e+00
  5.68934268e-01 -2.87894815e-01 -3.00394448e+00  1.70056302e+00
 -1.76008387e+

In [9]:
# 数组幂运算
print('数组幂运算的结果为：\n', arr1**arr2)

数组幂运算的结果为：
 [0.00000000e+00 1.95907015e+01 8.78304542e+00 1.49834566e+01
 4.60717266e+00 5.87896511e-01 4.21913622e-02 1.21917884e+00
 1.71605863e+00 7.43534617e+01 2.39858075e+00 3.89980467e-02
 6.76792721e-01 5.71903629e-01 7.75852303e+00 4.55500026e+00
 6.38978980e+00 3.27572611e-01 3.56996048e+00 6.35507049e-01
 1.23680841e+00 8.71325374e-01 2.49786587e+00 1.42313009e+00
 1.31603014e+00 3.32570328e+00 2.32309940e+00 8.20817102e-01
 1.83533675e+00 6.06618688e+00 6.82037685e+00 2.61746559e-01
 5.43819899e-01 1.00331752e+01 7.21802017e-01 1.38211545e+00
 4.69984495e+00 2.17384174e+00 4.72295378e-01 1.10197811e+00
 4.14905405e-01 2.82709145e-01 2.86995489e+00 1.95819359e+00
 1.80506979e+00 1.83402462e+00 7.73206038e-01 7.33746973e-01
 8.57048725e-01 2.10479663e+00 8.20551743e-01 3.11571923e-01
 5.16513647e-01 8.59577962e-01 8.91878859e-01 8.12380516e-01
 5.65122190e-01 3.04327274e+00 1.11090570e+00 8.32719047e-01
 1.19021838e+00 1.52970496e+00 1.39847818e+00 3.48358168e-01
 7.58888725e

In [10]:
# 数组排序
print('原始数组为：\n', arr1)
print('排序后的数组为：\n', np.sort(arr1))
print('去重后的数组为：\n', np.unique(arr1))

原始数组为：
 [0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]
排序后的数组为：
 [0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0

In [13]:
arr1.shape = 10, 10
print('重新设置shape的数组为：', arr1)

重新设置shape的数组为： [[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09]
 [0.1  0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19]
 [0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29]
 [0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39]
 [0.4  0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49]
 [0.5  0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59]
 [0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69]
 [0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79]
 [0.8  0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89]
 [0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99]]


In [ ]:
# 进行统计计算
